#cloud-config

hostname: "protos"

install:
  auto: true
  reboot: true
  device: auto
  grub_options:
    default_menu_entry: "Protos"

bundles:
  - targets:
      - run://quay.io/kairos/community-bundles:kairos-operator_latest

users:
  - name: "mauro"
    groups: ["admin"]
    ssh_authorized_keys: 
      - github:mauromorales

k0s:
  enabled: true
  args:
    - --enable-worker
    - --no-taints

stages:
  initramfs:
    - name: "Enable mDNS services to advertise hostname on local network"
      systemctl:
        enable:
          - avahi-daemon
  'provider-kairos.bootstrap.after.k0s-ready':
    - name: "Generate k0s kubeconfig"
      commands: |
        if k0s kubeconfig admin > /etc/k0s/kubeconfig.yaml 2>/dev/null; then
          chmod 0644 /etc/k0s/kubeconfig.yaml
          chown root:root /etc/k0s/kubeconfig.yaml
        fi
    - name: "Set KUBECONFIG for root user"
      commands: |
        if [ -f /etc/k0s/kubeconfig.yaml ]; then
          if ! grep -q '^export KUBECONFIG="/etc/k0s/kubeconfig.yaml"' /root/.bashrc 2>/dev/null; then
            printf '\nexport KUBECONFIG="/etc/k0s/kubeconfig.yaml"\n' >> /root/.bashrc
            chmod 0644 /root/.bashrc
            chown root:root /root/.bashrc
          fi
        fi
    - name: "Save KUBECONFIG on external storage"
      commands: |
        if [ -e /etc/k0s/kubeconfig.yaml ]; then
          curl -X POST -H "Content-Type: application/json" \
            -d "$(jq -n --arg path "/nodes/protos/kubeconfig.yaml" --arg content "$(cat /etc/k0s/kubeconfig.yaml)" '{path: $path, content: $content}')" \
            http://epictetus.local:8080/api/storage
        fi
