version: 2
updates:
  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore"
      include: "scope"

  # Docker dependencies for kairos node
  - package-ecosystem: "docker"
    directory: "/nodes/kairos"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "chore"
      include: "scope"

  # Docker dependencies for protos node
  - package-ecosystem: "docker"
    directory: "/nodes/protos"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "chore"
      include: "scope"

  # Docker dependencies for thuroros node
  - package-ecosystem: "docker"
    directory: "/nodes/thuroros"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "chore"
      include: "scope"

  # Docker dependencies for noos node
  - package-ecosystem: "docker"
    directory: "/nodes/noos"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "chore"
      include: "scope"