name: 'Build NoOS image'

on:
  push:
    branches:
      - 'main'
    paths:
      - 'nodes/noos/Dockerfile'
  pull_request:
    paths:
      - 'nodes/noos/Dockerfile'

permissions:
  contents: write
  security-events: write
  id-token: write
  actions: read
jobs:
  noos-base:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Login to Quay
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64
          file: nodes/noos/Dockerfile
          tags: quay.io/mauromorales/noos:base-${{ github.sha }}
          labels: "quay.expires-after=2d"
          push: true
  noos:
    name: Kairos Factory
    needs: noos-base
    uses: kairos-io/kairos-factory-action/.github/workflows/reusable-factory.yaml@v0.0.7
    secrets:
      registry_username: ${{ secrets.REGISTRY_USERNAME }}
      registry_password: ${{ secrets.REGISTRY_PASSWORD }}
    with:
      base_image: quay.io/mauromorales/noos:base-${{ github.sha }}
      model: "generic"
      arch: "amd64"
      version: "auto"
      iso: true
      grype: true
      registry_domain: "quay.io"
      registry_namespace: "mauromorales"
      registry_repository: "noos"
      summary_artifacts: true
      kubernetes_distro: "k0s"
      kubernetes_version: "v1.33.3+k0s.0"
      custom_tag_format: "$VERSION"
      custom_artifact_format: "noos-$VERSION"
      custom_job_name_format: "noos"
      cloud_config: nodes/noos/cloud-config.yaml
      image_labels: "quay.expires-after=2d"