name: 'Build Homelab images'

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  pull_request:

permissions:
  contents: write
  security-events: write
  id-token: write
  actions: read
jobs:
  base:
    name: Base Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Quay
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64, linux/arm64
          file: images/Dockerfile
          tags: quay.io/mauromorales/ubuntu:24.04-${{ github.sha }}
          push: true

  kairos:
    name: Kairos Factory
    needs: base
    uses: kairos-io/kairos-factory-action/.github/workflows/reusable-factory.yaml@main
    secrets:
      registry_username: ${{ secrets.REGISTRY_USERNAME }}
      registry_password: ${{ secrets.REGISTRY_PASSWORD }}
    with:
      base_image: quay.io/mauromorales/ubuntu:24.04-${{ github.sha }}
      model: "generic"
      arch: "amd64"
      version: "auto"
      iso: true
      grype: true
      registry_domain: "quay.io"
      registry_namespace: "mauromorales"
      summary_artifacts: true
      kubernetes_distro: "k0s"
      kubernetes_version: "v1.33.3+k0s.0"